language: python
python:
  - 3.7
os:
  - linux
  - windows
  - macOS
before_install:
  - pip install pytest
  - pip install codecov
install:
  - pip install ashar # install package + test dependencies
# allow gui output
services:
  - xvfb
script:
  - pytest  # pytest command won't be found
after_success:
  - codecov  # codecov command won't be found
