language: python
python:
  - 3.7
os:
  - linux
  - windows
  - macOS
before_install:
  - pip install codecov
install:
  - pip install ashar # install package + test dependencies
# allow gui output
services:
  - xvfb
script:
  - python -m setup.py  # pytest command won't be found
after_success:
  - python -m codecov  # codecov command won't be found
