language: python
python:
  - 3.7
os:
  - linux
  - windows
  - macOS
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
install:
  - pip install ashar # install package + test dependencies
script: python -m pytest  # pytest command won't be found
after_success: python -m codecov  # codecov command won't be found
