name: Github Container Registry

on:
  push:
    branches:
      - main

jobs:
  dockerloginbuildpush:
    runs-on: ubuntu-latest
    steps:
      #- uses: docker/login-action@v2
      - name: login to GitHub Container Registry
        run: export CR_PAT=${{ secrets.CR_PAT }}
        run: echo $CR_PAT | docker login ghcr.io --username ${{ github.actor }} --password-stdin
      - uses: actions/checkout@v2
      - name: create image from repository
        run: docker build -t ghcr.io/${{ github.actor }}/hiphp .
      - name: push image to GitHub Container Registry
        run: docker push ghcr.io/${{ github.actor }}/hiphp:latest
