name: Github Container Registry

on:
  push:
    branches:
      - main

jobs:
  dockerloginbuildpush:
    runs-on: ubuntu-latest
    steps:
      #- uses: docker/login-action@v2
      - name: login to GitHub Container Registry
        run: docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.CR_PAT }}
      - uses: actions/checkout@v2
      - name: create image from repository
        run: docker build -t ghcr.io/${{ github.actor }}/hiphp .
      - name: push image to GitHub Container Registry
        run: docker push ghcr.io/${{ github.actor }}/hiphp:latest
