name: Test Requirements on MacOs-latest | python 3.7->3.9
on: [push]
#defaults:
#  run:
#    working-directory: wrdir
jobs:
  #deploy:
  #  runs-on: windows-latest
  #  steps:
  #    - name: install readline
  #      run: python -m pip install readline
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [macos-latest] #,windows-latest
        python-version: [3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{matrix.python-version}}
        uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python-version}}
          # Optional - x64 or x86 architecture, defaults to x64
          architecture: 'x64'
      # You can test your matrix by printing the current Python version
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      #- name: Create Workspace Folder
      #  run: mkdir -p wrdir && mkdir -p wrdir/hiphp-tk && mkdir -p wrdir/hiphp-desktop && mkdir -p wrdir/hiphp-win
      #- name: Copy Files & folders to Workspace Folder
      #  run: cp hiphp-win/install_all_requirements_win.bat wrdir/hiphp-win/install_all_requirements_win.bat && cp requirements.txt wrdir/requirements.txt && cp requirements-pypi.txt wrdir/requirements-pypi.txt && cp hiphp-desktop/requirements-dst.txt wrdir/hiphp-desktop/requirements-dst.txt && cp hiphp-tk/requirements-tk.txt wrdir/hiphp-tk/requirements-tk.txt && cp hiphp-win/requirements-win.txt wrdir/hiphp-win/requirements-win.txt
      #- name: Create Config.ini file
      #  run: |
      #      python -c "import sys; open('wrdir/config.ini', 'w+').write('python_default_path='+sys.executable)"
      - name: pip Upgrade
        run: python -m pip install --upgrade pip
      #- name: Run
      #  run: wrdir/hiphp-win/install_all_requirements_win.bat
      - name: test requirements.txt
      run: pip install -r requirements.txt
      - name: test requirements-pypi.txt
      run: pip install -r requirements-pypi.txt
      - name: test hiphp-desktop/requirements-dst.txt
      run: pip install -r hiphp-desktop/requirements-dst.txt
      - name: test hiphp-tk/requirements-tk.txt
      run: pip install -r hiphp-tk/requirements-tk.txt
      #- name: test hiphp-win/requirements-win.txt
      #run: pip install -r hiphp-win/requirements-win.txt

